### ISSUE TITLE
NES using DESEQ2

### ISSUE THREAD

**Issue by ConorSmithTCD** [saezlab/dorothea#48]
Hi,
I was just wondering could you help with a query I have. I was following your vignette for bulk RNA-seq TF analysis and when I reached the part involving NES I wasn't sure which column to use from my data. In the vignette you use the t column, coming from limma differential gene expression analysis, however I used DESEQ2 for my differential gene expression and don't have a t column. Which column should I use instead? Is the 'stat' column the equivalent in DESEQ2?

Thanks,
Conor

**Comment by christianholland** [comment]
Hi @ConorSmithTCD,

in principle you could use any gene level statistic. In the first place you could use the log-fold changes, however, since this metric does not consider the variance in the data it might be better to use the test statistic, e.g. the t-value from limma or the stat column from DESeq2.

Cheers,
Christian
