### ISSUE TITLE
Discrepancy in dataset sizes

### ISSUE THREAD

**Issue by deeenes** [saezlab/dorothea#54]
The `entire_database` data frame contains 1,019,220 unique TF-target pairs, while the `dorothea_hs` only 454,504. 564,716 interactions from the former missing from the latter. The missing interactions are from all confidence levels:

```{r}
library(dorothea)
library(dplyr)

entire_database %>%
left_join(dorothea_hs, by = c('tf', 'target')) %>%
filter(is.na(confidence.y)) %>%
count(confidence.x)
# # A tibble: 5 x 2
#   confidence.x      n
#   <chr>         <int>
# 1 A                32
# 2 B              8073
# 3 C             10690
# 4 D            260365
# 5 E            285556
```

In addition, at 1,638 interactions the confidence level is different between `entire_database` and `dorothea_hs`:

```{r}
entire_database %>%
inner_join(dorothea_hs, by = c('tf', 'target')) %>%
filter(confidence.x != confidence.y) %>%
nrow
# [1] 1638
```

I could not find out the reason of these differences, and I am wondering whether is this normal?

**Comment by christianholland** [comment]
Hi @deeenes,
sorry for the late reply. Indeed the difference in the number of interactions is intended and refers to the following paragraph of the [original manuscript](https://genome.cshlp.org/content/29/8/1363): 

`To provide the most confident regulon for each TF, we aggregated the TF–target interactions with the highest possible confidence score that resulted in a regulon equal to or greater than 10 targets. The final confidence score assigned to the TF regulon is the lowest confidence score of its component targets.`

This involves also the change of the confidence level for some of the interactions, so everything is alright. 

Just to clarify: In my opinion the object `entire_database` shouldn't be used for TF estimation but rather as lookup table since for each individual TF-target interaction the source/reference is provided.

**Comment by dbdimitrov** [comment]
Also, the large number of interactions missing from dorothea_hs are such that are undirected (i.e. `mor` is 0).

**Comment by deeenes** [comment]
Thanks both for the answers, I tag here @sigven who originally asked the question

**Comment by christianholland** [comment]
@dbdimitrov just to clarify: the only filtering was done based on the "top 10 targets" approach and not based on the mode of regulation. Still you are right saying that in the `entire_database` there are interactions with the mode of regulation of 0. For those interactions that survived the filtering and having an mor of 0 we assumed an activator relationship by default
