### ISSUE TITLE
 The cell annotation need be corrected, after use "dorothea" for FindClusters

### ISSUE THREAD

**Issue by JohnsonHan** [saezlab/dorothea#60]
Thanks for sharing, DoRothEA is a very useful for me. 
In the demo script "TF activity inference from scRNA-seq data with DoRothEA as regulon resource." (https://saezlab.github.io/dorothea/articles/single_cell_vignette.html).
After you use "dorothea" for FindClusters, the cluster is not the same as the previous one using "RNA" for FindClusters, but you use the same Assigning cell type identity to clusters, resulting in wrong cell annotations and needs to be corrected：
`
## Assigning cell type identity to clusters
new.cluster.ids <- c("Naive CD4 T", "Memory CD4 T", "CD14+ Mono", "B", "CD8 T", 
                     "FCGR3A+ Mono", "NK", "DC", "Platelet") # This is a wrong cell annotation.

`

**Comment by dbdimitrov** [comment]
Hi @JohnsonHan,

Thanks for noticing. All together, I was not a fan of the clustering by TF activities being in the example.
I see it more as a proof of concept rather than how one should use DoRothEA. 

With this in mind, I have now completely removed this part of the single-cell vignette, and instead focus simply on the estimation of TF activities at the single-cell level.

Cheers,
Daniel
