### ISSUE TITLE
Installing DoRothEA

### ISSUE THREAD

**Issue by arnaudmeng** [saezlab/dorothea#7]
Dear authors, 

I would like first to thank you for your work and for making it available publicly. 

I would like to perform some tests using your tool but I encoutered some difficulties to install it. 

Just to let you know that I first tried to install the BioConductor version of DoRothEA but it seems that it is not available for both R 3.6.1 nor R 3.6.3
I also wasn't able to find the BioConductor help vignette using the keyword "DoRothEA". 
Is DoRothEA maintained in BioConductor ?

I then turn to the Github version and I figured out that R version >= 4.0 is needed to install DoRothEA, however I don't have this R version and I cannot update shared ressources we have in my institution. 

Do you plan to make DoRothEA available to lower R versions ? 

Thank you very much in advance for your response. 

Best regards

**Comment by alberto-valdeolivas** [comment]
Hello @arnaudmeng,

Many thanks for your interest in our work. 

Your issue is related to the fact that we are right now submitting our package to Bioconductor. It recently get accepted and it will be release in the next Bioconductor update by the end of this month. New packages in Bioconductor should be aligned with the lastest R version (R 4.0 is also about to be released by the end of this month). 

My suggestion is to install R 4.0 because, at some point, you will have to do it. Mainly if you want to keep using Bioconductor new packages and the lastest versions of existing packages.

There is a potential turnaround if you cannot install the new version of R in the near future. You can fork this repository into your own github account. In this forked repository, you can reduce the required R version in the description file of the package. Then, you install the package it from your own github repository. However, we cannot assure that everything will work and we cannot give you support, because our package is now tested in R 4.0. 

Hope it helps and best regards.

**Comment by arnaudmeng** [comment]
Hello, 

Thank you for your very quick response that is very appreciated. 
I finally managed to access R 4.0 and I succeed to install DoRothEA without trouble.

I am now trying some tests on a Seurat object I've analyze previously but I encountered a new issue where I lack memory to compute the VIPER score at this step : 

`
pbmc <- run_viper(seurat.integrated, regulon, options = list(method = "scale", minsize = 4, eset.filter = FALSE, cores = 1, verbose = FALSE))
 `

The memory usage by R exceed 32Go for the 18,000 cells Seurat integrated object that we have, and R returns : 

> Error: enabled to allocate a vector of size 4.6 Go
> Error: no more error handlers available (recursive errors?); invoking 'abort' restart

I need further time to perform additional tests. 

But I think it is another issue that do not match this topic. 

Again thank you very much for your help.

Best regards.

**Comment by christianholland** [comment]
Interesting. If the sample size is too large for a local machine we usually encounter this error message:

` Error: vector memory exhausted (limit reached?) `

For these cases we then compute the TF activities on high performance cluster. 

I think you error is more related to the allocated memory to R. You could increase the allocated memory using the function `memory.limit()`
